steps:
  # install dependencies
  - name: "node"
    entrypoint: "yarn"
    args: ["install"]
  # build
  - name: "node"
    entrypoint: "yarn"
    args: ["build"]
    env:
      [
        "REACT_APP_API_ENDPOINT=$_API_URL",
        "REACT_APP_CHAT_URL=$_CLIENT_APP_URL",
      ]
  # build Image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west6-docker.pkg.dev/opentech-332213/fg/$REPO_NAME/$BRANCH_NAME/$_DEPLOYMENT:$COMMIT_SHA",
        "-t",
        "europe-west6-docker.pkg.dev/opentech-332213/fg/$REPO_NAME/$BRANCH_NAME/$_DEPLOYMENT:latest",
        ".",
      ]
  # Push Image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west6-docker.pkg.dev/opentech-332213/fg/$REPO_NAME/$BRANCH_NAME/$_DEPLOYMENT:$COMMIT_SHA",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west6-docker.pkg.dev/opentech-332213/fg/$REPO_NAME/$BRANCH_NAME/$_DEPLOYMENT:latest",
      ]
  - name: "ubuntu"
    env:
      - "SSH_KEY=$_SSH_KEY"
      - "DEPLOYMENT=$_DEPLOYMENT"
      - "NAMESPACE=$_NAMESPACE"
      - "IMAGE=europe-west6-docker.pkg.dev/opentech-332213/fg/$REPO_NAME/$BRANCH_NAME/$_DEPLOYMENT:$COMMIT_SHA"
    script: |
      #!/usr/bin/env bash
      echo $SSH_KEY | base64 -d > ./.ssh_key
      chmod 400 ./.ssh_key
      apt update
      apt install -y openssh-client
      ssh -i ./.ssh_key -o StrictHostKeyChecking=no ubuntu@136.243.57.185 "kubectl set image deployment/$DEPLOYMENT $DEPLOYMENT=$IMAGE -n $NAMESPACE"
images:
  - "europe-west6-docker.pkg.dev/opentech-332213/fg/$REPO_NAME/$BRANCH_NAME/$_DEPLOYMENT:$COMMIT_SHA"
